In [14]:
import pandas as pd

In [15]:
Demo= pd.read_csv('Demografia2021.csv')
Demo

    FIPS  Poblacion      Lat      Long
0      1    5049196  32.3182  -86.9023
1      2     734420  61.3707 -152.4044
2      4     727407  33.7298 -111.4312
3      5    3026870  34.9697  -92.3731
4      6   39142565  36.1162 -119.6816
5      8    5814036  39.0598 -105.3111
6      9    3606607  41.5978  -72.7554
7     10    1005062  39.3185  -75.5071
8     11     669256  38.8974  -77.0268
9     12   21831949  27.7663  -81.6868
10    13   10792060  33.0406  -83.6431
11    15    1447029  21.0943 -157.4983
12    16    1904848  44.2405 -114.4788
13    17   12700641  40.3495  -88.9861
14    18    6815907  39.8494  -86.2583
15    19    3198613  42.0115  -93.2105
16    20    2938338  38.5266  -96.7265
17    21    4507583  37.6681  -84.6701
18    22    4627971  31.1695  -91.8678
19    23    1378931  44.6939  -69.3819
20    24    6179403  39.0639  -76.8021
21    25    7000474  42.2302  -71.5301
22    26   10041351  43.3266  -84.5361
23    27    5718660  45.6945  -93.9002
24    28    2947209  32.7416  -89.6787
25    29    6171374  38.4561  -92.2884
26    30    1106522  46.9219 -110.4544
27    31    1964537  41.1254  -98.2681
28    32    3148141  38.3135 -117.0554
29    33    1387677  43.4525  -71.5639
30    34    9270541  40.2989  -74.5210
31    35    2117333  34.8405 -106.2485
32    36   19848276  42.1657  -74.9481
33    37   10564320  35.6301  -79.8064
34    38     777966  47.5289  -99.7840
35    39   11767344  40.3888  -82.7649
36    40    3992238  35.5653  -96.9289
37    41    4254280  44.5720 -122.0709
38    42   13015571  40.5908  -77.2098
39    44    1097246  41.6809  -71.5118
40    45    5194274  33.8569  -80.9450
41    46     896492  44.2998  -99.4388
42    47    6965740  35.7478  -86.6923
43    48   29570351  31.0545  -97.5635
44    49    3339738  40.1500 -111.8624
45    50     647210  44.0459  -72.7107
46    51    8658910  37.7693  -78.1700
47    53    7743760  47.4009 -121.4905
48    54    1785618  38.4912  -80.9545
49    55    5881608  44.2685  -89.6165
50    56     579636  42.7560 -107.3025

In [16]:
Demo.sort_values(by='Poblacion', ascending=False)

    FIPS  Poblacion      Lat      Long
4      6   39142565  36.1162 -119.6816
43    48   29570351  31.0545  -97.5635
9     12   21831949  27.7663  -81.6868
32    36   19848276  42.1657  -74.9481
38    42   13015571  40.5908  -77.2098
13    17   12700641  40.3495  -88.9861
35    39   11767344  40.3888  -82.7649
10    13   10792060  33.0406  -83.6431
33    37   10564320  35.6301  -79.8064
22    26   10041351  43.3266  -84.5361
30    34    9270541  40.2989  -74.5210
46    51    8658910  37.7693  -78.1700
47    53    7743760  47.4009 -121.4905
21    25    7000474  42.2302  -71.5301
42    47    6965740  35.7478  -86.6923
14    18    6815907  39.8494  -86.2583
20    24    6179403  39.0639  -76.8021
25    29    6171374  38.4561  -92.2884
49    55    5881608  44.2685  -89.6165
5      8    5814036  39.0598 -105.3111
23    27    5718660  45.6945  -93.9002
40    45    5194274  33.8569  -80.9450
0      1    5049196  32.3182  -86.9023
18    22    4627971  31.1695  -91.8678
17    21    4507583  37.6681  -84.6701
37    41    4254280  44.5720 -122.0709
36    40    3992238  35.5653  -96.9289
6      9    3606607  41.5978  -72.7554
44    49    3339738  40.1500 -111.8624
15    19    3198613  42.0115  -93.2105
28    32    3148141  38.3135 -117.0554
3      5    3026870  34.9697  -92.3731
24    28    2947209  32.7416  -89.6787
16    20    2938338  38.5266  -96.7265
31    35    2117333  34.8405 -106.2485
27    31    1964537  41.1254  -98.2681
12    16    1904848  44.2405 -114.4788
48    54    1785618  38.4912  -80.9545
11    15    1447029  21.0943 -157.4983
29    33    1387677  43.4525  -71.5639
19    23    1378931  44.6939  -69.3819
26    30    1106522  46.9219 -110.4544
39    44    1097246  41.6809  -71.5118
7     10    1005062  39.3185  -75.5071
41    46     896492  44.2998  -99.4388
34    38     777966  47.5289  -99.7840
1      2     734420  61.3707 -152.4044
2      4     727407  33.7298 -111.4312
8     11     669256  38.8974  -77.0268
45    50     647210  44.0459  -72.7107
50    56     579636  42.7560 -107.3025

In [17]:
# Paso 1: Ordenar los pesos (Población) de menor a mayor
df_sorted = Demo.sort_values(by='Poblacion', ascending=False)
df_sorted

    FIPS  Poblacion      Lat      Long
4      6   39142565  36.1162 -119.6816
43    48   29570351  31.0545  -97.5635
9     12   21831949  27.7663  -81.6868
32    36   19848276  42.1657  -74.9481
38    42   13015571  40.5908  -77.2098
13    17   12700641  40.3495  -88.9861
35    39   11767344  40.3888  -82.7649
10    13   10792060  33.0406  -83.6431
33    37   10564320  35.6301  -79.8064
22    26   10041351  43.3266  -84.5361
30    34    9270541  40.2989  -74.5210
46    51    8658910  37.7693  -78.1700
47    53    7743760  47.4009 -121.4905
21    25    7000474  42.2302  -71.5301
42    47    6965740  35.7478  -86.6923
14    18    6815907  39.8494  -86.2583
20    24    6179403  39.0639  -76.8021
25    29    6171374  38.4561  -92.2884
49    55    5881608  44.2685  -89.6165
5      8    5814036  39.0598 -105.3111
23    27    5718660  45.6945  -93.9002
40    45    5194274  33.8569  -80.9450
0      1    5049196  32.3182  -86.9023
18    22    4627971  31.1695  -91.8678
17    21    4507583  37.6681  -84.6701
37    41    4254280  44.5720 -122.0709
36    40    3992238  35.5653  -96.9289
6      9    3606607  41.5978  -72.7554
44    49    3339738  40.1500 -111.8624
15    19    3198613  42.0115  -93.2105
28    32    3148141  38.3135 -117.0554
3      5    3026870  34.9697  -92.3731
24    28    2947209  32.7416  -89.6787
16    20    2938338  38.5266  -96.7265
31    35    2117333  34.8405 -106.2485
27    31    1964537  41.1254  -98.2681
12    16    1904848  44.2405 -114.4788
48    54    1785618  38.4912  -80.9545
11    15    1447029  21.0943 -157.4983
29    33    1387677  43.4525  -71.5639
19    23    1378931  44.6939  -69.3819
26    30    1106522  46.9219 -110.4544
39    44    1097246  41.6809  -71.5118
7     10    1005062  39.3185  -75.5071
41    46     896492  44.2998  -99.4388
34    38     777966  47.5289  -99.7840
1      2     734420  61.3707 -152.4044
2      4     727407  33.7298 -111.4312
8     11     669256  38.8974  -77.0268
45    50     647210  44.0459  -72.7107
50    56     579636  42.7560 -107.3025

In [18]:
# Paso 2: Asegurarnos de que 'Poblacion' sea de tipo entero
df_sorted['Poblacion'] = df_sorted['Poblacion'].astype(int)

# Paso 3: Calcular las diferencias entre poblaciones consecutivas
df_sorted['diff'] = df_sorted['Poblacion'].diff().abs()  # Diferencias absolutas entre las poblaciones consecutivas

In [19]:
df_sorted

    FIPS  Poblacion      Lat      Long       diff
4      6   39142565  36.1162 -119.6816        NaN
43    48   29570351  31.0545  -97.5635  9572214.0
9     12   21831949  27.7663  -81.6868  7738402.0
32    36   19848276  42.1657  -74.9481  1983673.0
38    42   13015571  40.5908  -77.2098  6832705.0
13    17   12700641  40.3495  -88.9861   314930.0
35    39   11767344  40.3888  -82.7649   933297.0
10    13   10792060  33.0406  -83.6431   975284.0
33    37   10564320  35.6301  -79.8064   227740.0
22    26   10041351  43.3266  -84.5361   522969.0
30    34    9270541  40.2989  -74.5210   770810.0
46    51    8658910  37.7693  -78.1700   611631.0
47    53    7743760  47.4009 -121.4905   915150.0
21    25    7000474  42.2302  -71.5301   743286.0
42    47    6965740  35.7478  -86.6923    34734.0
14    18    6815907  39.8494  -86.2583   149833.0
20    24    6179403  39.0639  -76.8021   636504.0
25    29    6171374  38.4561  -92.2884     8029.0
49    55    5881608  44.2685  -89.6165   289766.0
5      8    5814036  39.0598 -105.3111    67572.0
23    27    5718660  45.6945  -93.9002    95376.0
40    45    5194274  33.8569  -80.9450   524386.0
0      1    5049196  32.3182  -86.9023   145078.0
18    22    4627971  31.1695  -91.8678   421225.0
17    21    4507583  37.6681  -84.6701   120388.0
37    41    4254280  44.5720 -122.0709   253303.0
36    40    3992238  35.5653  -96.9289   262042.0
6      9    3606607  41.5978  -72.7554   385631.0
44    49    3339738  40.1500 -111.8624   266869.0
15    19    3198613  42.0115  -93.2105   141125.0
28    32    3148141  38.3135 -117.0554    50472.0
3      5    3026870  34.9697  -92.3731   121271.0
24    28    2947209  32.7416  -89.6787    79661.0
16    20    2938338  38.5266  -96.7265     8871.0
31    35    2117333  34.8405 -106.2485   821005.0
27    31    1964537  41.1254  -98.2681   152796.0
12    16    1904848  44.2405 -114.4788    59689.0
48    54    1785618  38.4912  -80.9545   119230.0
11    15    1447029  21.0943 -157.4983   338589.0
29    33    1387677  43.4525  -71.5639    59352.0
19    23    1378931  44.6939  -69.3819     8746.0
26    30    1106522  46.9219 -110.4544   272409.0
39    44    1097246  41.6809  -71.5118     9276.0
7     10    1005062  39.3185  -75.5071    92184.0
41    46     896492  44.2998  -99.4388   108570.0
34    38     777966  47.5289  -99.7840   118526.0
1      2     734420  61.3707 -152.4044    43546.0
2      4     727407  33.7298 -111.4312     7013.0
8     11     669256  38.8974  -77.0268    58151.0
45    50     647210  44.0459  -72.7107    22046.0
50    56     579636  42.7560 -107.3025    67574.0

In [21]:
covid = pd.read_csv('Covid2021.csv')
covid

      FIPS  Week  Confirmed  Deaths  Incident_Rate  New_Cases  New_Deaths
0        1     1    2692473   35201    7844.676470      90859        4045
1        1     2    2877535   40108    8383.865356     185062        4907
2        1     3    3010889   44172    8772.399981     133354        4064
3        1     4    3143072   49862    9157.522829     132183        5690
4        1     5    3256946   56800    9489.301342     113874        6938
...    ...   ...        ...     ...            ...        ...         ...
2596    56    47     770227    9429   19011.787043       9851          98
2597    56    48     778636    9834   19219.349381       8409         405
2598    56    49     787385   10216   19435.304061       8749         382
2599    56    50     793177   10454   19578.270057       5792         238
2600    56    51     798040   10634   19698.305216       4863         180

[2601 rows x 7 columns]

In [22]:
# Crear el DataFrame

# Paso 1: Calcular la Población Susceptible a partir de los Nuevos Casos y la Tasa de Incidencia
covid['Susceptible'] = (covid['New_Cases'] * 1000) / covid['Incident_Rate']

# Mostrar los resultados
covid

,FIPS,Week,Confirmed,Deaths,Incident_Rate,New_Cases,New_Deaths,Susceptible
0,1,1,2692473,35201,7844.676470,90859,4045,11582.249484
1,1,2,2877535,40108,8383.865356,185062,4907,22073.589226
2,1,3,3010889,44172,8772.399981,133354,4064,15201.541231
3,1,4,3143072,49862,9157.522829,132183,5690,14434.362051
4,1,5,3256946,56800,9489.301342,113874,6938,12000.251219
...,...,...,...,...,...,...,...,...
2596,56,47,770227,9429,19011.787043,9851,98,518.152238
2597,56,48,778636,9834,19219.349381,8409,405,437.527818
2598,56,49,787385,10216,19435.304061,8749,382,450.160181
2599,56,50,793177,10454,19578.270057,5792,238,295.838191
2600,56,51,798040,10634,19698.305216,4863,180,246.874030

In [24]:
# Guardar el DataFrame en un archivo CSV
covid.to_csv('Covid2021_1.csv', index=False)

In [25]:

covFip= covid.copy()

# Lista de FIPS que deseas filtrar
fips_deseados = [41, 40, 9, 49, 19, 32, 5, 28, 20]

# Filtrar el DataFrame para obtener solo los FIPS deseados
covFip = covFip[covFip['FIPS'].isin(fips_deseados)]

# Mostrar el nuevo DataFrame
covFip

,FIPS,Week,Confirmed,Deaths,Incident_Rate,New_Cases,New_Deaths,Susceptible
153,5,1,1696259,27188,8029.769802,64883,1262,8080.306360
154,5,2,1835317,29215,8688.044116,139058,2027,16005.673791
155,5,3,1936722,31089,9168.076238,101405,1874,11060.662823
156,5,4,2022725,33141,9575.198200,86003,2052,8981.850632
157,5,5,2103882,34807,9959.380113,81157,1666,8148.800335
...,...,...,...,...,...,...,...,...
2290,49,47,4121288,24241,18364.414898,70126,470,3818.580684
2291,49,48,4184618,24741,18646.612695,63330,500,3396.327313
2292,49,49,4252559,25299,18949.357059,67941,558,3585.398691
2293,49,50,4305951,25767,19187.271235,53392,468,2782.678128
2294,49,51,4352425,26170,19394.358878,46474,403,2396.263795

In [26]:
covFip["FIPS"].unique()

array([ 5,  9, 19, 20, 28, 32, 40, 41, 49])